In [1]:
COCO_CATS = ['__background__', 'airplane', 'apple', 'backpack', 'banana', 'baseball bat', 'baseball glove', 'bear',
             'bed', 'bench', 'bicycle', 'bird', 'boat', 'book', 'bottle', 'bowl', 'broccoli', 'bus', 'cake', 'car',
             'carrot', 'cat', 'cell phone', 'chair', 'clock', 'couch', 'cow', 'cup', 'dining table', 'dog', 'donut',
             'elephant', 'fire hydrant', 'fork', 'frisbee', 'giraffe', 'hair drier', 'handbag', 'horse', 'hot dog',
             'keyboard', 'kite', 'knife', 'laptop', 'microwave', 'motorcycle', 'mouse', 'orange', 'oven',
             'parking meter', 'person', 'pizza', 'potted plant', 'refrigerator', 'remote', 'sandwich', 'scissors',
             'sheep', 'sink', 'skateboard', 'skis', 'snowboard', 'spoon', 'sports ball', 'stop sign', 'suitcase',
             'surfboard', 'teddy bear', 'tennis racket', 'tie', 'toaster', 'toilet', 'toothbrush', 'traffic light',
             'train', 'truck', 'tv', 'umbrella', 'vase', 'wine glass', 'zebra']

In [6]:
coco_ids = {'airplane': 5, 'apple': 53, 'backpack': 27, 'banana': 52,
            'baseball bat': 39, 'baseball glove': 40, 'bear': 23, 'bed': 65,
            'bench': 15, 'bicycle': 2, 'bird': 16, 'boat': 9, 'book': 84,
            'bottle': 44, 'bowl': 51, 'broccoli': 56, 'bus': 6, 'cake': 61,
            'car': 3, 'carrot': 57, 'cat': 17, 'cell phone': 77, 'chair': 62,
            'clock': 85, 'couch': 63, 'cow': 21, 'cup': 47, 'dining table':
            67, 'dog': 18, 'donut': 60, 'elephant': 22, 'fire hydrant': 11,
            'fork': 48, 'frisbee': 34, 'giraffe': 25, 'hair drier': 89,
            'handbag': 31, 'horse': 19, 'hot dog': 58, 'keyboard': 76, 'kite':
            38, 'knife': 49, 'laptop': 73, 'microwave': 78, 'motorcycle': 4,
            'mouse': 74, 'orange': 55, 'oven': 79, 'parking meter': 14,
            'person': 1, 'pizza': 59, 'potted plant': 64, 'refrigerator': 82,
            'remote': 75, 'sandwich': 54, 'scissors': 87, 'sheep': 20, 'sink':
            81, 'skateboard': 41, 'skis': 35, 'snowboard': 36, 'spoon': 50,
            'sports ball': 37, 'stop sign': 13, 'suitcase': 33, 'surfboard':
            42, 'teddy bear': 88, 'tennis racket': 43, 'tie': 32, 'toaster':
            80, 'toilet': 70, 'toothbrush': 90, 'traffic light': 10, 'train':
            7, 'truck': 8, 'tv': 72, 'umbrella': 28, 'vase': 86, 'wine glass':
            46, 'zebra': 24}

coco_ids_to_cats = dict(map(reversed, list(coco_ids.items())))

index = 16
new_index = -1
cats_to_ids = dict(map(reversed, enumerate(COCO_CATS)))
coco_ids_to_alphabetical = {k: cats_to_ids[v] for k, v in coco_ids_to_cats.items()}
for key in coco_ids_to_alphabetical:
    if key == index:
        new_index = coco_ids_to_alphabetical[key]
        break
if new_index == -1:
    raise ValueError('Something is wrong!')

new_index

11

In [2]:
from maskrcnn_benchmark.data.transforms.build import build_transforms
from yacs.config import CfgNode

/mnt/disk1/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/tqdm-4.66.2-py3.7.egg/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/mnt/disk1/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/apex-0.1-py3.7.egg/apex/__init__.py:68: DeprecatedFeatureWarning: apex.amp is deprecated and will be removed by the end of February 2023. Use [PyTorch AMP](https://pytorch.org/docs/stable/amp.html)
  warnings.warn(msg, DeprecatedFeatureWarning)


In [3]:
voc_args = {'data_dir': 'data/VOCdevkit/VOC2007',
 'split': 'trainval', 
 'use_difficult': False, 
 'external_proposal': False, 
 'old_classes': [], 
 'new_classes': ['aeroplane', 'bicycle', 'bird', 'boat', 'bottle', 'bus', 'car', 'cat', 'chair', 'cow'], 
 'excluded_classes': ['diningtable', 'dog', 'horse', 'motorbike', 'person', 'pottedplant', 'sheep', 'sofa', 'train', 'tvmonitor'], 
 'is_train': True, 
 'cfg': CfgNode({'MODEL': CfgNode({'RPN_ONLY': False, 'MASK_ON': False, 'RETINANET_ON': False, 
                                    'KEYPOINT_ON': False, 'DEVICE': 'cuda', 
                                    'META_ARCHITECTURE': 'GeneralizedRCNN', 'CLS_AGNOSTIC_BBOX_REG': False,
                                    'WEIGHT': 'catalog://ImageNetPretrained/MSRA/R-50', 'SOURCE_WEIGHT': '', 
                                    'BACKBONE': CfgNode({'CONV_BODY': 'R-50-C4', 'FREEZE_CONV_BODY_AT': 2, 
                                                        'USE_GN': False, 'ALL_FREEZE': False, 'FPN_FREEZE': False
                                                        }),
                                    'FPN': CfgNode({'USE_GN': False, 'USE_RELU': False}), 
                                    'GROUP_NORM': CfgNode({'DIM_PER_GP': -1, 'NUM_GROUPS': 32, 'EPSILON': 1e-05}), 
                                    'RPN': CfgNode({'USE_FPN': False, 'ANCHOR_SIZES': (32, 64, 128, 256, 512), 
                                                    'ANCHOR_STRIDE': (16,), 'ASPECT_RATIOS': (0.5, 1.0, 2.0), 'STRADDLE_THRESH': 0, 
                                                    'FG_IOU_THRESHOLD': 0.7, 'BG_IOU_THRESHOLD': 0.3, 'BATCH_SIZE_PER_IMAGE': 256, 
                                                    'POSITIVE_FRACTION': 0.5, 'PRE_NMS_TOP_N_TRAIN': 12000, 'PRE_NMS_TOP_N_TEST': 6000, 
                                                    'POST_NMS_TOP_N_TRAIN': 2000, 'POST_NMS_TOP_N_TEST': 1000, 'NMS_THRESH': 0.7, 'MIN_SIZE': 0, 
                                                    'FPN_POST_NMS_TOP_N_TRAIN': 2000, 'FPN_POST_NMS_TOP_N_TEST': 2000, 'FPN_POST_NMS_PER_BATCH': True, 
                                                    'RPN_HEAD': 'SingleConvRPNHead', 'EXTERNAL_PROPOSAL': False, 'CONV_FREEZE': False, 'CLS_FREEZE': False, 'BBS_FREEZE': False
                                                    }), 
                                    'ROI_HEADS': CfgNode({'USE_FPN': False, 'FG_IOU_THRESHOLD': 0.5, 'BG_IOU_THRESHOLD': 0.5, 'BBOX_REG_WEIGHTS': (10.0, 10.0, 5.0, 5.0),
                                                        'BATCH_SIZE_PER_IMAGE': 512, 'POSITIVE_FRACTION': 0.25, 'FC_FREEZE': False, 'CLS_FREEZE': False, 'BBS_FREEZE': False, 
                                                        'CLS_OFFSET': False, 'BBS_OFFSET': False, 'SCORE_THRESH': 0.05, 'NMS': 0.5, 'DETECTIONS_PER_IMG': 100
                                                        }), 
                                    'ROI_BOX_HEAD': CfgNode({'FEATURE_EXTRACTOR': 'ResNet50Conv5ROIFeatureExtractor', 
                                                            'PREDICTOR': 'FastRCNNPredictor', 'POOLER_RESOLUTION': 7, 
                                                            'POOLER_SAMPLING_RATIO': 2, 'POOLER_SCALES': (0.0625,), 'NUM_CLASSES': 11,
                                                            'NAME_OLD_CLASSES': [], 
                                                            'NAME_NEW_CLASSES': ['aeroplane', 'bicycle', 'bird', 'boat', 'bottle', 'bus', 'car', 'cat', 'chair', 'cow'], 
                                                            'NAME_EXCLUDED_CLASSES': ['diningtable', 'dog', 'horse', 'motorbike', 'person', 'pottedplant', 'sheep', 'sofa', 'train', 'tvmonitor'], 
                                                            'MLP_HEAD_DIM': 1024, 'USE_GN': False, 'DILATION': 1, 'CONV_HEAD_DIM': 256, 'NUM_STACKED_CONVS': 4
                                                            }), 
                                    'ROI_MASK_HEAD': CfgNode({'FEATURE_EXTRACTOR': 'ResNet50Conv5ROIFeatureExtractor', 'PREDICTOR': 'MaskRCNNC4Predictor', 
                                                            'POOLER_RESOLUTION': 14, 'POOLER_SAMPLING_RATIO': 0, 'POOLER_SCALES': (0.0625,), 'MLP_HEAD_DIM': 1024, 
                                                            'CONV_LAYERS': (256, 256, 256, 256), 'RESOLUTION': 14, 'SHARE_BOX_FEATURE_EXTRACTOR': True, 
                                                            'POSTPROCESS_MASKS': False, 'POSTPROCESS_MASKS_THRESHOLD': 0.5, 'DILATION': 1, 'USE_GN': False
                                                            }),
                                    'ROI_KEYPOINT_HEAD': CfgNode({'FEATURE_EXTRACTOR': 'KeypointRCNNFeatureExtractor', 'PREDICTOR': 'KeypointRCNNPredictor', 'POOLER_RESOLUTION': 14, 
                                                                'POOLER_SAMPLING_RATIO': 0, 'POOLER_SCALES': (0.0625,), 'MLP_HEAD_DIM': 1024, 'CONV_LAYERS': (512, 512, 512, 512, 512, 512, 512, 512),
                                                                'RESOLUTION': 14, 'NUM_CLASSES': 17, 'SHARE_BOX_FEATURE_EXTRACTOR': True
                                                                }), 
                                    'RESNETS': CfgNode({'NUM_GROUPS': 1, 'WIDTH_PER_GROUP': 64, 'STRIDE_IN_1X1': True, 'TRANS_FUNC': 'BottleneckWithFixedBatchNorm', 
                                                        'STEM_FUNC': 'StemWithFixedBatchNorm', 'RES5_DILATION': 1, 'BACKBONE_OUT_CHANNELS': 1024, 
                                                        'RES2_OUT_CHANNELS': 256, 'STEM_OUT_CHANNELS': 64, 'STAGE_WITH_DCN': (False, False, False, False),
                                                        'WITH_MODULATED_DCN': False, 'DEFORMABLE_GROUPS': 1
                                                        }), 
                                    'RETINANET': CfgNode({'NUM_CLASSES': 81, 'ANCHOR_SIZES': (32, 64, 128, 256, 512), 
                                                        'ASPECT_RATIOS': (0.5, 1.0, 2.0), 'ANCHOR_STRIDES': (8, 16, 32, 64, 128), 
                                                        'STRADDLE_THRESH': 0, 'OCTAVE': 2.0, 'SCALES_PER_OCTAVE': 3, 'USE_C5': True, 
                                                        'NUM_CONVS': 4, 'BBOX_REG_WEIGHT': 4.0, 'BBOX_REG_BETA': 0.11, 'PRE_NMS_TOP_N': 1000,
                                                        'FG_IOU_THRESHOLD': 0.5, 'BG_IOU_THRESHOLD': 0.4, 'LOSS_ALPHA': 0.25, 'LOSS_GAMMA': 2.0,
                                                        'PRIOR_PROB': 0.01, 'INFERENCE_TH': 0.05, 'NMS_TH': 0.4
                                                        }), 
                                    'FBNET': CfgNode({'ARCH': 'default', 'ARCH_DEF': '', 'BN_TYPE': 'bn', 'SCALE_FACTOR': 1.0, 'WIDTH_DIVISOR': 1,
                                                    'DW_CONV_SKIP_BN': True, 'DW_CONV_SKIP_RELU': True, 'DET_HEAD_LAST_SCALE': 1.0, 'DET_HEAD_BLOCKS': [], 
                                                    'DET_HEAD_STRIDE': 0, 'KPTS_HEAD_LAST_SCALE': 0.0, 'KPTS_HEAD_BLOCKS': [], 'KPTS_HEAD_STRIDE': 0, 
                                                    'MASK_HEAD_LAST_SCALE': 0.0, 'MASK_HEAD_BLOCKS': [], 'MASK_HEAD_STRIDE': 0, 'RPN_HEAD_BLOCKS': 0, 'RPN_BN_TYPE': ''
                                                    })
                                    }), 
            'INPUT': CfgNode({'MIN_SIZE_TRAIN': (800,), 'MAX_SIZE_TRAIN': 1333, 'MIN_SIZE_TEST': 800, 'MAX_SIZE_TEST': 1333, 'FLIP_PROB_TRAIN': 0.5, 'PIXEL_MEAN': [102.9801, 115.9465, 122.7717], 
                                'PIXEL_STD': [1.0, 1.0, 1.0], 'TO_BGR255': True, 'BRIGHTNESS': 0.0, 'CONTRAST': 0.0, 'SATURATION': 0.0, 'HUE': 0.0}), 
            'DATASETS': CfgNode({'TRAIN': ('voc_rb_2007_trainval',), 'TEST': ('voc_2007_test',)}), 
            'DATALOADER': CfgNode({'NUM_WORKERS': 4, 'SIZE_DIVISIBILITY': 32, 'ASPECT_RATIO_GROUPING': True}), 
            'SOLVER': CfgNode({'MAX_ITER': 10000, 'BASE_LR': 0.005, 'BIAS_LR_FACTOR': 2, 'MOMENTUM': 0.9, 'WEIGHT_DECAY': 0.0001, 'WEIGHT_DECAY_BIAS': 0, 'GAMMA': 0.1, 'STEPS': (7500,), 
                                'WARMUP_FACTOR': 0.3333333333333333, 'WARMUP_ITERS': 500, 'WARMUP_METHOD': 'linear', 'CHECKPOINT_PERIOD': 2500, 'IMS_PER_BATCH': 4}), 
            'TEST': CfgNode({'EXPECTED_RESULTS': [], 'EXPECTED_RESULTS_SIGMA_TOL': 4, 'IMS_PER_BATCH': 4, 'DETECTIONS_PER_IMG': 100, 'COCO_ALPHABETICAL_ORDER': False}), 
            'OUTPUT_DIR': 'output/10-10/LR005_BS4_FILOD', 
            'TENSORBOARD_DIR': './tensorboardx', 
            'PATHS_CATALOG': '/mnt/disk1/tiennh/IOD/ABR_IOD/maskrcnn_benchmark/config/paths_catalog.py', 
            'INCREMENTAL': False, 
            'DIST': CfgNode({'ROI_ALIGN': False, 'TYPE': 'l2', 'RPN': False, 'FEAT': False, 'ATT': False, 'ALPHA': 0.0, 'BETA': 0.0, 'GAMMA': 1.0}), 
            'UCE_WEIGHT': 1.0, 
            'MEM_BUFF': None, 
            'MEM_TYPE': False, 
            'IS_SAMPLE': False, 
            'IS_FATHER': True, 
            'DTYPE': 'float32', 
            'CLS_PER_STEP': -1, 
            'AMP_VERBOSE': False}), 
#  'transforms':
}

NameError: name 'cfg' is not defined

In [5]:
cfg = voc_args['cfg']
transform = build_transforms(cfg, is_train=True)
voc_args['transforms'] = transform

In [6]:
cfg.SOLVER.IMS_PER_BATCH = 1

In [7]:
coco_args = {'root': 'coco/train2017', 'ann_file': 'coco/annotations/instances_train2017.json', 'transforms':transform }

In [8]:
from maskrcnn_benchmark.data.datasets.coco import COCODataset
from maskrcnn_benchmark.data.datasets.voc_abr import PascalVOCDataset_ABR

In [9]:
# coco_dataset = COCODataset(**coco_args)
voc_dataset = PascalVOCDataset_ABR(**voc_args)

voc.py | in training mode


In [10]:
# data_loader
from torch.utils.data import DataLoader

from maskrcnn_benchmark.data.build import make_data_loader 

voc_loader = make_data_loader(cfg, is_train=True, is_distributed=False) 




-------------------------------------------------
-------------------------------------------------
voc.py | in training mode
('voc_rb_2007_trainval',)
Dataset voc_rb_2007_trainval contains 2868 images.


In [11]:
# target[1].get_field('labels') 
len(voc_dataset)

2868

In [25]:
import torch

In [28]:
count = 0 
for img, target, proposal, index in voc_loader: 
    print(target[0].get_field('labels'))

tensor([9])
tensor([7])
tensor([2, 2, 2, 9, 9, 9])
tensor([6])
tensor([3])
tensor([9])
tensor([2, 2, 2, 2, 2])
tensor([3])
tensor([7, 7])
tensor([3])
tensor([9, 9])
tensor([7])
tensor([9])
tensor([6])
tensor([7, 7])
tensor([7, 7])
tensor([7, 7, 7, 7, 7, 7])
tensor([2, 2, 2, 2])
tensor([2])
tensor([7])
tensor([4])
tensor([2])
tensor([6])
tensor([4])
tensor([7, 7])
tensor([1])
tensor([10])
tensor([1])
tensor([1])
tensor([8])
tensor([9, 9, 9])
tensor([1])
tensor([3])
tensor([8])
tensor([7])
tensor([7])
tensor([7])
tensor([9])
tensor([1])
tensor([9])
tensor([9])
tensor([1])
tensor([7, 7])
tensor([6])
tensor([5])
tensor([3])
tensor([7, 7, 7])
tensor([3])
tensor([7])
tensor([8])
tensor([4])
tensor([9, 9, 9])
tensor([10, 10])
tensor([4])
tensor([4])
tensor([3, 3])
tensor([2, 2])
tensor([9])
tensor([7, 7])
tensor([7, 7])
tensor([7])
tensor([8])
tensor([3])
tensor([6])
tensor([7])
tensor([10, 10, 10])
tensor([2, 2, 2])
tensor([7, 4])
tensor([7])
tensor([9])
tensor([7])
tensor([7, 7])
tensor([8]

KeyboardInterrupt: 

In [27]:
target[].get_field('labels') 

tensor([3, 3, 3])

In [22]:
image = Image.open('data/VOCdevkit/VOC2007/JPEGImages/009946.jpg').convert("RGB")

In [24]:
type(image) 

PIL.Image.Image

In [ ]:

# Get all attributes and methods of the object
all_attributes_and_methods = dir(voc_dataset)

for attr in all_attributes_and_methods:
    print(attr)
    # print(getattr(voc_dataset, attr))
    print('---------------------')

In [13]:
len(voc_dataset), len(coco_dataset)

(2868, 31235)

In [25]:
# make data loader coco 
from maskrcnn_benchmark.data.build import make_data_sampler, make_batch_data_sampler
import torch
from maskrcnn_benchmark.data.collate_batch import BatchCollator

sampler = make_data_sampler(coco_dataset, True, False, 1, 0)
aspect_grouping = [1]
images_per_gpu = 4 
num_iters = 10000
start_iter = 0
batch_sampler = make_batch_data_sampler(coco_dataset, sampler, aspect_grouping, images_per_gpu, num_iters, start_iter)
collator = BatchCollator(cfg.DATALOADER.SIZE_DIVISIBILITY)
num_workers = cfg.DATALOADER.NUM_WORKERS



In [15]:
data_loader = torch.utils.data.DataLoader(coco_dataset, batch_sampler=batch_sampler,
                                                  collate_fn=collator, num_workers=num_workers)

In [26]:
start_iter = 0 
for iteration, (images, targets, proposals, _) in enumerate(data_loader, start_iter): 
    print(iteration)
    print(images)
    print(targets)
    print(proposals)
    break

0
(BoxList(num_boxes=1, image_width=1066, image_height=800, mode=xyxy), BoxList(num_boxes=2, image_width=1000, image_height=800, mode=xyxy), BoxList(num_boxes=3, image_width=1066, image_height=800, mode=xyxy), BoxList(num_boxes=2, image_width=1199, image_height=800, mode=xyxy))
(None, None, None, None)


In [32]:

sampler = make_data_sampler(voc_dataset, True, False, 1, 0)
aspect_grouping = [1]
images_per_gpu = 4 
num_iters = 10000
start_iter = 0
batch_sampler = make_batch_data_sampler(voc_dataset, sampler, aspect_grouping, images_per_gpu, num_iters, start_iter)
collator = BatchCollator(cfg.DATALOADER.SIZE_DIVISIBILITY)
num_workers = cfg.DATALOADER.NUM_WORKERS
voc_loader = torch.utils.data.DataLoader(voc_dataset, batch_sampler=batch_sampler,
                                                  collate_fn=collator, num_workers=num_workers)



In [33]:
len(voc_loader)

10000

In [34]:
len( voc_dataset.final_ids)

2868

In [35]:
print(len(voc_dataset), len(voc_loader))
for (images, targets, proposals, _) in voc_loader: 
    print(images)
    print(targets)
    print(proposals)
    break

2868 10000
(BoxList(num_boxes=1, image_width=1066, image_height=800, mode=xyxy), BoxList(num_boxes=1, image_width=1066, image_height=800, mode=xyxy), BoxList(num_boxes=1, image_width=1204, image_height=800, mode=xyxy), BoxList(num_boxes=3, image_width=1332, image_height=749, mode=xyxy))
(None, None, None, None)


In [18]:

coco_dataset.id_to_img_map

{0: 30,
 1: 34,
 2: 36,
 3: 64,
 4: 71,
 5: 94,
 6: 127,
 7: 138,
 8: 151,
 9: 154,
 10: 164,
 11: 208,
 12: 257,
 13: 283,
 14: 308,
 15: 315,
 16: 326,
 17: 349,
 18: 359,
 19: 450,
 20: 510,
 21: 540,
 22: 560,
 23: 562,
 24: 595,
 25: 636,
 26: 643,
 27: 659,
 28: 692,
 29: 699,
 30: 711,
 31: 714,
 32: 716,
 33: 723,
 34: 731,
 35: 754,
 36: 762,
 37: 790,
 38: 795,
 39: 827,
 40: 839,
 41: 909,
 42: 923,
 43: 939,
 44: 1053,
 45: 1090,
 46: 1099,
 47: 1102,
 48: 1122,
 49: 1139,
 50: 1144,
 51: 1155,
 52: 1171,
 53: 1213,
 54: 1216,
 55: 1228,
 56: 1237,
 57: 1244,
 58: 1264,
 59: 1306,
 60: 1315,
 61: 1319,
 62: 1340,
 63: 1342,
 64: 1347,
 65: 1355,
 66: 1374,
 67: 1381,
 68: 1393,
 69: 1424,
 70: 1451,
 71: 1501,
 72: 1518,
 73: 1523,
 74: 1554,
 75: 1562,
 76: 1577,
 77: 1590,
 78: 1591,
 79: 1592,
 80: 1611,
 81: 1622,
 82: 1667,
 83: 1712,
 84: 1722,
 85: 1739,
 86: 1757,
 87: 1777,
 88: 1779,
 89: 1790,
 90: 1799,
 91: 1803,
 92: 1822,
 93: 1840,
 94: 1877,
 95: 1902,
 96:

In [5]:
NUM_OLD_CATEGORY = 70  # do not include background
NUM_NEW_CATEGORY = 10  # number of added categories


COCO_VOC_CATS = ['__background__', 'airplane', 'bicycle', 'bird', 'boat',
                 'bottle', 'bus', 'car', 'cat', 'chair', 'cow', 'dining table',
                 'dog', 'horse', 'motorcycle', 'person', 'potted plant',
                 'sheep', 'couch', 'train', 'tv']

COCO_NONVOC_CATS = ['apple', 'backpack', 'banana', 'baseball bat',
                    'baseball glove', 'bear', 'bed', 'bench', 'book', 'bowl',
                    'broccoli', 'cake', 'carrot', 'cell phone', 'clock', 'cup',
                    'donut', 'elephant', 'fire hydrant', 'fork', 'frisbee',
                    'giraffe', 'hair drier', 'handbag', 'hot dog', 'keyboard',
                    'kite', 'knife', 'laptop', 'microwave', 'mouse', 'orange',
                    'oven', 'parking meter', 'pizza', 'refrigerator', 'remote',
                    'sandwich', 'scissors', 'sink', 'skateboard', 'skis',
                    'snowboard', 'spoon', 'sports ball', 'stop sign',
                    'suitcase', 'surfboard', 'teddy bear', 'tennis racket',
                    'tie', 'toaster', 'toilet', 'toothbrush', 'traffic light',
                    'truck', 'umbrella', 'vase', 'wine glass', 'zebra']

# COCO_CATS = COCO_VOC_CATS+COCO_NONVOC_CATS
COCO_CATS = ['__background__', 'airplane', 'apple', 'backpack', 'banana', 'baseball bat', 'baseball glove', 'bear',
             'bed', 'bench', 'bicycle', 'bird', 'boat', 'book', 'bottle', 'bowl', 'broccoli', 'bus', 'cake', 'car',
             'carrot', 'cat', 'cell phone', 'chair', 'clock', 'couch', 'cow', 'cup', 'dining table', 'dog', 'donut',
             'elephant', 'fire hydrant', 'fork', 'frisbee', 'giraffe', 'hair drier', 'handbag', 'horse', 'hot dog',
             'keyboard', 'kite', 'knife', 'laptop', 'microwave', 'motorcycle', 'mouse', 'orange', 'oven',
             'parking meter', 'person', 'pizza', 'potted plant', 'refrigerator', 'remote', 'sandwich', 'scissors',
             'sheep', 'sink', 'skateboard', 'skis', 'snowboard', 'spoon', 'sports ball', 'stop sign', 'suitcase',
             'surfboard', 'teddy bear', 'tennis racket', 'tie', 'toaster', 'toilet', 'toothbrush', 'traffic light',
             'train', 'truck', 'tv', 'umbrella', 'vase', 'wine glass', 'zebra']

coco_ids = {'airplane': 5, 'apple': 53, 'backpack': 27, 'banana': 52,
            'baseball bat': 39, 'baseball glove': 40, 'bear': 23, 'bed': 65,
            'bench': 15, 'bicycle': 2, 'bird': 16, 'boat': 9, 'book': 84,
            'bottle': 44, 'bowl': 51, 'broccoli': 56, 'bus': 6, 'cake': 61,
            'car': 3, 'carrot': 57, 'cat': 17, 'cell phone': 77, 'chair': 62,
            'clock': 85, 'couch': 63, 'cow': 21, 'cup': 47, 'dining table':
            67, 'dog': 18, 'donut': 60, 'elephant': 22, 'fire hydrant': 11,
            'fork': 48, 'frisbee': 34, 'giraffe': 25, 'hair drier': 89,
            'handbag': 31, 'horse': 19, 'hot dog': 58, 'keyboard': 76, 'kite':
            38, 'knife': 49, 'laptop': 73, 'microwave': 78, 'motorcycle': 4,
            'mouse': 74, 'orange': 55, 'oven': 79, 'parking meter': 14,
            'person': 1, 'pizza': 59, 'potted plant': 64, 'refrigerator': 82,
            'remote': 75, 'sandwich': 54, 'scissors': 87, 'sheep': 20, 'sink':
            81, 'skateboard': 41, 'skis': 35, 'snowboard': 36, 'spoon': 50,
            'sports ball': 37, 'stop sign': 13, 'suitcase': 33, 'surfboard':
            42, 'teddy bear': 88, 'tennis racket': 43, 'tie': 32, 'toaster':
            80, 'toilet': 70, 'toothbrush': 90, 'traffic light': 10, 'train':
            7, 'truck': 8, 'tv': 72, 'umbrella': 28, 'vase': 86, 'wine glass':
            46, 'zebra': 24}

coco_ids_to_cats = dict(map(reversed, list(coco_ids.items())))

min_keypoints_per_image = 10


def dict_slice(adict, start, end):
    keys = list(adict.keys())
    # print('keys : {0}'.format(keys))
    # print('length of keys: {0}'.format(len(keys)))
    # adict is coco_ids_to_cats
    dict_slice = {}
    for k in keys[start: end]:
        dict_slice[k] = adict[k]
    # print('dict_slice: {0}'.format(dict_slice))
    return dict_slice

In [3]:
train_data_cats_dict = dict_slice(coco_ids_to_cats, NUM_OLD_CATEGORY, (NUM_OLD_CATEGORY + NUM_NEW_CATEGORY))
train_data_cats_index = list(train_data_cats_dict.keys()) 

train_data_cats_index

[70, 90, 10, 7, 8, 72, 28, 86, 46, 24]

In [8]:

def convert_cats_from_original_order_to_alphabetical_order(index):
    new_index = -1
    cats_to_ids = dict(map(reversed, enumerate(COCO_CATS)))
    coco_ids_to_alphabetical = {k: cats_to_ids[v] for k, v in coco_ids_to_cats.items()}
    for key in coco_ids_to_alphabetical:
        if key == index:
            new_index = coco_ids_to_alphabetical[key]
            break
    if new_index == -1:
        raise ValueError('Something is wrong!')
    return new_index



convert_cats_from_original_order_to_alphabetical_order(5)

1